# Numpy #

NumPy is a powerful Python library for numerical computing. It provides efficient array structures and functions to perform operations on them.


## 1. Importing Numpy ##

First, import the NumPy library. It's common practice to import it as np for convenience:

In [3]:
import numpy as np

## 2. Creating Arrays ##
You can create NumPy arrays from Python lists or tuples.

### a. One-Dimensional Array ###
Let's create a one-dimensional array representing the ages of five individuals:

In [6]:
ages = np.array([20,14,28,40,7])
print(ages)

[20 14 28 40  7]


### b. Two-Dimensional Array ###
Now, create a two-dimensional array representing the scores of three students in four subjects:

In [8]:
scores = np.array([[85, 90, 78, 92],
                   [88, 76, 85, 80],
                   [90, 88, 82, 85]])
print("Scores:\n", scores)

Scores:
 [[85 90 78 92]
 [88 76 85 80]
 [90 88 82 85]]


## 3. Array Attributes ##
NumPy arrays have several attributes that provide information about the array.​

### .shape ###
Returns the dimensions (rows, columns, etc.) of the array as a tuple.
Helps understand the structure of data.

Example:

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


### .ndim ###
Tells you the number of dimensions (or axes) the array has.
Helps you identify if the array is 1D, 2D, 3D, etc.

Example:

In [13]:
print(arr.ndim)

2


### .size ###
Gives the total number of elements in the array.

Quick way to know how much data you're working with.

Example:

In [15]:
print(arr.size)

6


### .T (Transpose) ###
Flips the array over its diagonal—turns rows into columns and columns into rows. Very handy for linear algebra and when reshaping data.

Example:

In [17]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


### .flat ###
Returns an iterator over all elements of the array (as if it were flattened).​

Example:

In [31]:
for elem in arr.flat:
    print(elem, end = ", ")

1, 2, 3, 4, 5, 6, 

Check this numpy cheat sheet for more detailed methods and attributes:
https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python